### ISSUE TITLE
no longer works/multiple issues with the package and other stuff

### ISSUE THREAD

**Issue by rwynx** [mvartuc/Perculus-Downloader#2]
is this project abandoned? or should i make a list about issues?

**Comment by mvartuc** [comment]
Chrome has changed the extension structure since I've made this project and for some reason github doesn't notify me when someone opens an issue. I'll take a look and try to restructure the project this week. Thanks for letting me know.

**Comment by rwynx** [comment]
Alright, i'll be watching this repo for updates, I hope you decide to work on it again.
